name: 'zhr-action Demo'

on:
  workflow_dispatch:
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    # 可以参考 https://crontab.guru/ 进行配置
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - username: ZJU_USERNAME # han
            password: ZJU_PASSWORD
            # 如果出现登录异常，可以配置 ZJU_COOKIE secret，请参考 https://github.com/upupming/zhr-action#%E7%99%BB%E5%BD%95%E5%BC%82%E5%B8%B8 获取 ZJU_COOKIE 的值
            cookie_eai_sess: ZJU_COOKIE
            dingtalk_token: DINGTALK_TOKEN
             
          - username: ZJU_USERNAME1 # zhaoyi 3200300142
            password: ZJU_PASSWORD1
            dingtalk_token: DINGTALK_TOKEN

          - username: ZJU_USERNAME2 # siuhong 3200300602
            password: ZJU_PASSWORD2 
            dingtalk_token: DINGTALK_TOKEN
          
          - username: ZJU_USERNAME3 # tanhii 3200300315
            password: ZJU_PASSWORD3
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME4 # weiling 3200300262
            password: ZJU_PASSWORD4
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME5 # gaobai 3190300394
            password: ZJU_PASSWORD5
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME6 # zhenxiao 3210300297
            password: ZJU_PASSWORD6
            dingtalk_token: DINGTALK_TOKEN 
            
          - username: ZJU_USERNAME7 # yihong 3190300876
            password: ZJU_PASSWORD7
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME8 # jason 3200300334 
            password: ZJU_PASSWORD8
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME9 # yiteng 3190300285
            password: ZJU_PASSWORD9
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME10 # tanhii npy 22240083
            password: ZJU_PASSWORD10
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME11 # yenyi 3200300296
            password: ZJU_PASSWORD11
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME12 # melvin 321300062
            password: ZJU_PASSWORD12
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME13 # cslim 3190300304
            password: ZJU_PASSWORD13
            dingtalk_token: DINGTALK_TOKEN
          
          - username: ZJU_USERNAME14 # rongxiang 3200300414
            password: ZJU_PASSWORD14
            dingtalk_token: DINGTALK_TOKEN
            
          - username: ZJU_USERNAME15 # weixian 3200300109
            password: ZJU_PASSWORD15
            dingtalk_token: DINGTALK_TOKEN
          
    steps:
      - name: 打卡
        uses: upupming/zhr-action@release
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          cookie_eai_sess: ${{ secrets[matrix.cookie_eai_sess] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
        env:
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
